#!/usr/bin/env python
# This file is part of Palabra
#
# Copyright (C) 2009 - 2011 Simeon Visser
#
# Palabra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

try:
    import pygtk
    pygtk.require("2.0")
    import gtk
except (ImportError, AssertionError):
    print "PyGTK 2.8 or higher is required for this application."
    raise SystemExit

import palabralib.constants as constants
from palabralib.files import read_containers
from palabralib.gui import PalabraWindow, create_splash
import palabralib.preferences as preferences
from palabralib.preferences import read_config_file
from palabralib.word import create_wordlists

#import pstats
#import cProfile
#cProfile.runctx('self.update_window(True)', globals(), locals(), filename='fooprof')
#p = pstats.Stats('fooprof')
#p.sort_stats('time').print_stats(20)

if __name__ == "__main__":
    has_splash = False
    try:
        if has_splash:
            splash = create_splash()
            splash.show()
            while gtk.events_pending():
                gtk.main_iteration()
        print "Reading configuration file..."
        read_config_file()
        print "Loading wordlists..."
        wordlists = create_wordlists(preferences.prefs["word_files"])
        print "Loading pattern files..."
        patternfiles = constants.STANDARD_PATTERN_FILES + preferences.prefs["pattern_files"]
        patterns = read_containers(patternfiles)
        
        palabra = PalabraWindow()
        palabra.wordlists.update(wordlists)
        palabra.stores = palabra.construct_list_stores()
        palabra.patterns = patterns
        palabra.show_all()
        if has_splash:
            splash.destroy()
        gtk.main()
    except KeyboardInterrupt:
        import sys
        sys.exit("ERROR: Interrupted by user")
else:
    raise ImportError("Palabra cannot be imported.")
